

env:
  name: 01_tiktok

name: 01_tiktok

on:
  push:
    branches: [ deploy ]
    paths: ['01_tiktok/**','.github/workflows/01_tiktok.yml]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Using ssh
        uses: appleboy/ssh-action@master
        with:
          host: 194.233.90.140
          username: app
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            [ -d web_clone_exercise ] || git clone git@github.com:radenfajrus/web_clone_exercise.git
            cd web_clone_exercise
            git stash
            git checkout deploy
            git pull
            cd ${{ env.name }}
            npm install -g vite
            npm install
            vite build

